language: cpp

matrix:
  include:
    - os: linux
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
    - os: linux
      env: MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-4.0
            - libstdc++-5-dev
    - os: linux
      env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - libstdc++-5-dev

# prevent Travis from overwriting our CXX variables
before_install:
    - eval "${MATRIX_EVAL}"
    - echo $CXX

script:
    - mkdir build
    - cd build
    - cmake --config Debug ..
    - cmake --build . -- -j2
    - ctest --output-on-failure
